seed: 3407

# Directory settings
root_dir: "/home/cr7/CMXFS/"
abs_dir: "."
dataset_name: "PST900"
dataset_path: "/home/cr7/MMFS/datasets/PST900"

# Dataset Config
rgb_folder: "RGB"
rgb_format: ".png"
x_folder: "Modal"
x_format: ".png"
text_root_folder: "datasets/PST900/Text_Bert" # "datasets/PST900/Text"
text_format: ".npy" # ".txt"
guide_root_folder: "datasets/PST900/Guide"
guide_format: ".png"
label_folder: "Label"
label_format: ".png"
gt_transform: false

# Classes and labels
num_classes: 5
class_names: ['Background', 'Hand-Drill', 'BackPack', 'Fire-Extinguisher', 'Survivor']
pattale: [
    [0, 0, 0],  # Background  0
    [228, 228, 179],  # Hand-Drill 1
    [133, 57, 181],  # BackPack 2
    [177, 162, 67],  # Fire-Extinguisher 3
    [50, 178, 200],  # Survivor 4
  ]
labels: ['Hand-Drill', 'BackPack', 'Fire-Extinguisher', 'Survivor']
# Image Config
x_is_single_channel: true
train_source: "datasets/PST900/train.txt"
eval_source: "datasets/PST900/test.txt"
is_test: false
num_train_imgs: 597
num_eval_imgs: 288
background: 255
image_height: 480
image_width: 640 
norm_mean: [0.485]
norm_std: [0.229]

# Network Config
backbone: 'vmamba_tiny'
pretrained_backbone: null
decoder: "MLPDecoder"
decoder_embed_dim: 512

# Training Config
align_corners: False
optimizer: "AdamW"
lr: 0.00006 #0.0001
lr_power: 0.9
momentum: 0.9
weight_decay: 0.01
batch_size: 4 #2 #8
nepochs: 500
num_workers: 16
fix_bias: true
bn_eps: 0.001
bn_momentum: 0.1
train_scale_array: [0.5, 0.75, 1, 1.25, 1.5, 1.75]
warm_up_epoch: 10

# Loss config
lambda_reg: 0.5 # loss_language
lambda_coeff: 1 # loss_language
alpha: 0.5 # loss_in
beta: 0.2 # loss_grad
gamma: 1 # loss_color
theta: 1 # loss_seg
sigma: 0.1 # loss_fusion
Gamma_coeff: 0.5
Contrast_coeff: 1.8

# Evaluation Config
verbose: False
eval_stride_rate: 0.6667
eval_scale_array: [1]
eval_flip: false
is_flip: false
eval_crop_size: [720, 1280]

# Checkpoint settings
checkpoint_start_epoch: 100
checkpoint_step: 5
checkpoint_dir: "experiment/PST900/exp/checkpoint"
log_dir_link: "experiment/PST900/exp"
log_dir: "experiment/PST900/exp"
tb_dir: "experiment/PST900/exp/tb"

# Result settings
save_path: "./experiment/PST900/exp/result"

# Log file settings
log_file: "experiment/PST900/exp/train_output.log"
link_log_file: "experiment/PST900/exp/log_last.log"
val_log_file: "experiment/PST900/exp/val_output.log"
link_val_log_file: "experiment/PST900/exp/val_last.log"
test_log_file: "experiment/PST900/exp/test_output.log"